### ISSUE TITLE
css yingyang 阴阳太极图

### ISSUE THREAD

**Issue by gaoryrt** [bczFE/articles#12]
`<div class="yinyang"></div>`
请填写yinyang的css

**Comment by gaoryrt** [comment]
`background-image: data:xxx`
base64 background image

**Comment by gaoryrt** [comment]
```css
    #yin-yang {
      width: 96px;
      box-sizing: content-box;
      height: 48px;
      background: #eee;
      border-color: red;
      border-style: solid;
      border-width: 2px 2px 50px 2px;
      border-radius: 100%;
      position: relative;
    }
    #yin-yang:before {
      content: "";
      position: absolute;
      top: 50%;
      left: 0;
      background: #eee;
      border: 18px solid red;
      border-radius: 100%;
      width: 12px;
      height: 12px;
      box-sizing: content-box;
    }
    #yin-yang:after {
      content: "";
      position: absolute;
      top: 50%;
      left: 50%;
      background: red;
      border: 18px solid #eee;
      border-radius: 100%;
      width: 12px;
      height: 12px;
      box-sizing: content-box;
    }
```

**Comment by gaoryrt** [comment]
```
.yingyang:after {
    content: '☯'
}
```
utf-8 emoji

**Comment by gaoryrt** [comment]
`background-image:url('data:image/svg+xml;charset=UTF-8,<svg>...</svg>')`
inline svg background image

**Comment by gaoryrt** [comment]
```css
  .yinyang {
      position: relative;
      height: 100px;
      width: 0;
      border-radius: 100px;
      border-left: black 50px solid;
      border-right: white 50px solid;
      filter: drop-shadow(0 0 1px black);
    }
    .yinyang:before,
    .yinyang:after {
      position: absolute;
      content: '';
      height: 20px;
      width: 20px;
      border-radius: 25px;
      border: 15px solid #000;
      background: #fff;
      z-index: 2;
      top: 0;
      left: -25px;

    }
    .yinyang:after {
      top: 50px;
      border: 15px solid #fff;
      background: #000;
    }
```
伪元素版2
