### ISSUE TITLE
iPhone XR 的镂空文字特效

### ISSUE THREAD

**Issue by gaoryrt** [bczFE/articles#4]
![image](https://user-images.githubusercontent.com/5306513/47560611-549ab600-d94b-11e8-9ebe-fa0585b10488.png)

关键属性还是 `-webkit-background-clip: text`

**Comment by gaoryrt** [comment]
大概是下面这样：

```html
<div class="background-img">
	<p class="background-clip">lorem ipsum</p>
</div>
```

```css
.backgound-img {
	background-image: url(...)
}
.background-clip {
	-webkit-background-clip: text;
	-webkit-text-fill-color: transparent;
	color: #0000 !important
}
```
