### ISSUE TITLE
分界变色效果

### ISSUE THREAD

**Issue by gaoryrt** [bczFE/articles#6]
> 这个不好描述，看图：

![oct-30-2018 10-33-19](https://user-images.githubusercontent.com/5306513/47692012-42f92d00-dc2f-11e8-87f6-a1808690d778.gif)

或者是到[原网站](http://www.parakeet.co/)看右上方

首先想到的还是不同的 filter 来对 nav 进行颜色 filter
右键看了下，原来是每个 section 都有对应颜色的 nav，用 clip 进行蒙版的操作

**Comment by gaoryrt** [comment]
大概是这样：
```html
<section>
	<i class="_red"></i>
</section>
<section>
	<i class="_blue"></i>
</section>
<section>
	<i class="_green"></i>
</section>
```

```css
section {
	clip: rect(auto, auto, auto, auto);
	-webkit-clip-path: inset(0 0 0 0);
	clip-path: inset(0 0 0 0);
}
```
