### ISSUE TITLE
全宽的上方阴影

### ISSUE THREAD

**Issue by gaoryrt** [bczFE/articles#8]
![image](https://user-images.githubusercontent.com/5306513/49005553-f824f380-f1a1-11e8-83e5-f018b8e614dd.png)

👆要达到这个效果，底 bar 在可滚动内容上有一个上阴影

放大一点：
![image](https://user-images.githubusercontent.com/5306513/49005515-dcb9e880-f1a1-11e8-9028-51e8f76a665a.png)

**Comment by gaoryrt** [comment]
`box-shadow` 的语法：
```css
.sub-bar {
  /* offset-x | offset-y | blur-radius | spread-radius | color */
  box-shadow: 2px 2px 2px 1px rgba(0, 0, 0, 0.2);
}
```
这样通过缩小和平移，是可以写出来「上方阴影」的：
![image](https://user-images.githubusercontent.com/5306513/49006104-44246800-f1a3-11e8-9a3a-96718c3cd9d1.png)
```css
.sub-bar {
  box-shadow: 0 -5px 5px -5px rgba(0, 0, 0, 0.3)
}
```
![image](https://user-images.githubusercontent.com/5306513/49006236-99607980-f1a3-11e8-9064-0349df122cd6.png)

```css
.sub-bar {
  box-shadow: 0 -2.5px 5px -2.5px rgba(0, 0, 0, .3)
}
```
但是由于 blur 拥有圆角，**上方全宽的阴影会在左右溢出，左右不溢出的上方不能均匀全宽**。

![image](https://user-images.githubusercontent.com/5306513/49006386-f6f4c600-f1a3-11e8-83c9-e6778b9c4514.png)

把第二个例子的阴影颜色加深后如上图。单靠 `box-shadow`，不能做到单边全宽并且其他边不溢出。

**Comment by gaoryrt** [comment]
# 1. overflow: hidden
这个很简单，就是把左右的阴影给隐藏掉
```css
.container {
	position: relative;
	overflow-x: hidden;
	overflow-y: auto;
}
```

**Comment by gaoryrt** [comment]
# 2. clip-path
同样是把左右隐藏掉，使用 `clip-path` 不需要 container
```css
.sub-bar {
	 box-shadow: 0 0 5px rgba(0, 0, 0, 0.3);
     clip-path: polygon(0 -5px, 100% -5px, 100% 100%, 0% 100%)
}
```

**Comment by gaoryrt** [comment]
# 3. 阴影元素
不用 sub-bar 自带的阴影了，自己写一个
```css
.shadow {
    position: absolute;
    bottom: 20px;
    left: 0;
    width: 100%;
    height: 5px;
    background: linear-gradient(transparent, rgba(0, 0, 0, .15));
  }
```
