### ISSUE TITLE
css

### ISSUE THREAD

**Issue by gaoryrt** [bczFE/articles#9]

**Comment by gaoryrt** [comment]
这个就是个 [`shape-outside`](https://developer.mozilla.org/zh-CN/docs/Web/CSS/shape-outside)属性，使用也很简单：

```html
<body>
  <div class="shape"></div>
  <div class="text">Lorem ipsum ...</div>
</body>
```

```css
.shape {
  shape-outside: circle(50%);
  width: 500px;
  height: 500px;
  float: left;
}
```
